config/routes.rb
Rails.application.routes.draw do
  resources :users
  get    '/about',  to: 'static_pages#about'
  get    '/found',  to: 'static_pages#found'
  get    '/lost',  to: 'static_pages#lost'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  get    '/inform',  to: 'inform#new'
  post    '/inform', to:  'inform#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'static_pages#lost'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inform.rb
class Inform < ApplicationRecord
validates :username,  presence: true, length: { maximum: 40 } , uniqueness: { case_sensitive: false }
validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
validates :contact,  presence: true, length: { maximum: 255 }
validates :tel_number,  presence: true, length: { is: 10 } , numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
validates :username,  presence: true, length: { maximum: 40 } , uniqueness: { case_sensitive: false }
has_secure_password
validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
validates :contact,  presence: true, length: { maximum: 255 }
validates :tel_number,  presence: true, length: { is: 10 } , numericality: { only_integer: true }
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/inform_controller.rb
class InformController < ApplicationController
before_action :check_for_cancel, :only => [:create]

    def index
    end
    # define attr
    def new
        @user = User.new
    end
    
    # create user
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:info] = "Create Success!!."
            redirect_to root_url
        else
            render 'new'
        end
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def check_for_cancel
        if params[:commit] == "Reset"
        redirect_to '/signup'
        end
    end
    
    
    private
    #check input
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :contact, :tel_number)
    end
    
    

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :check_for_cancel, :only => [:create]

    def index
    end
    # define attr
    def new
        @user = User.new
    end
    
    # create user
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:info] = "Create Success!!."
            redirect_to root_url
        else
            render 'new'
        end
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def check_for_cancel
        if params[:commit] == "Reset"
        redirect_to '/signup'
        end
    end
    
    
    private
    #check input
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :contact, :tel_number)
    end
    
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.erb
<div class="footer" id ="footer-navbar" style="margin-top: 20px">
        <p>
          footer</p>
      </div>

app/views/layouts/_header.html.erb
<div id="navbar">
    <b><p class="title-name"><i class="fas fa-box-open"></i> Lost&Found</p></b>
    <% if logged_in? %>
        <%= link_to "Logout" , logout_path, :method => :delete %>
        <%= link_to "About" , about_path %>
        <%= link_to "Profile", current_user %>
        <%= link_to "Edit inform" , '#' %>
        <%= link_to "Inform" , inform_path %>
    <% else %>
        <%= link_to "Login" , login_path %>
        <%= link_to "About" , about_path %>
    <% end %>
    <%= link_to "Found Items" , found_path %>
    <%= link_to "Lost Items" , root_path %> 
</div>
<div class="about-header about-header-image project-topic">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><%= yield(:title) %> | LostAndFound</title>
 <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
        <link href="testproject/app/assets/stylesheets/bootstrap-material-design.css" rel="stylesheet">
        <link href="testproject/app/assets/stylesheets/main.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Quantico" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>
  <body>
        <%= render "layouts/header" %>
        <%= yield %>
        <%= render "layouts/footer" %>
      
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container"> 
    <div class="row">
        <div class="col-md-12">
            <div class="box-text-big" style="padding-bottom: 0px">
                <h3 class="project-topic text-center" style="margin-top: 5px">- About -</h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="box-text-big" style="border-right: solid  #66615b 0.75px ">
                <h3 class="project-topic text-center" style="margin-top: 5px">Lost & Found</h3>
                <h5 class="text-center title-thai">รายชื่อสมาชิก</h5>
                <div class="text-center">
                    <p style="line-height: 2em;">
                            นาย จีระวัฒน์ หนักแน่น 5710450031<br>
                            นาย ธีระพล ไวยนิยี 5810613413<br>
                            นางสาว ศิริรัตน์ บุณยัษเฐียร 5910490035<br>
                            นาย ภูริณัฐ ธรรมราช 5910613347
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box-text-big">
                <h3 class="project-topic text-center" style="margin-top: 5px">Document</h3>
                <div class="row " style="padding-top: 20px">
                    <div class="col-md-1"></div>
                    <div class="col-md-5"><p>
                        <a href="https://drive.google.com/file/d/1VLooRiRulXW0MOmTysG1FS6iJ3AfDUw6/view?usp=sharing"><font style="color:#009688"><i class="fas fa-file-download"></i> ไฟล์ข้อเสนอ</font></a><br><br>
                        <a href="https://drive.google.com/file/d/1CFpvjPLAAI06TLbod6XAZYnY0T1gnz15/view?usp=sharing"><font style="color:#009688"><i class="fas fa-file-download"></i> Feature</font></a><br><br>
                        <a href="https://drive.google.com/file/d/1xOnAmD5vzOSE_RLq4uDJr89DHqXEYyxf/view?usp=sharing"><font style="color:#009688"><i class="fas fa-file-download"></i> Storyboard</font></a></p>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5"><p>
                        <a href="https://drive.google.com/file/d/1ME-yGoZ0cqnUxqGe1vyvYMXLv-JT1EIx/view?usp=sharing"><font style="color:#009688"><i class="fas fa-file-download"></i> Requirements</font></a><br><br>
                        <a href="https://drive.google.com/file/d/1FDn9RGvmxJxXc8k5sMsCssJV8XSrMkKt/view?usp=sharing"><font style="color:#009688"><i class="fas fa-file-download"></i> ER-Diagram</font></a></p>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <div class="row">
        <div class=col-md-12>
            <div class="box-text-big head-topic text-center" style="margin-top: 40px">
                <h4 class="project-topic">- Link -</h4><hr>
                <button class="button-link" onclick="window.location.href='https://www.pivotaltracker.com/n/projects/2223207'">Privotal Tracker</button>
                <button class="button-link" onclick="window.location.href='https://bitbucket.org/5810613413/testproject/src/poo-master'">Bitbucket Repository</button>
                <button class="button-link" onclick="window.location.href='https://youtu.be/j3vNVj_tsYg'">Youtube</button>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/found.html.erb
<div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 5px">Found Items</h3>
             
            </div>
        </div>
    </div>
</div>

app/views/static_pages/login.html.erb
<div class="container">    
    <div class="section-box">
            <div class="row row-box">
                <div class="col-md-12" style="text-align: center;">
                    <div class="cardbox">
                    <h3 class="project-topic" style="margin-top: 5px">Sign in</h3>
                    
                </div>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/lost.html.erb
<div class="container">    
    <div class="box-text-big">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <h3 class="project-topic" style="margin-top: 5px">Lost Items</h3>

                </div>
            </div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <div class="row row-form">
        <div class="col-md-3 project-topic text-right">
            <%= f.label :username %>
        </div>
        <div class="col-md-6">
            <%= f.text_field :username , class: 'form-control' %>
        </div>
    </div>
    <div class="row row-form">
        <div class="col-md-3 project-topic text-right">
            <%= f.label :password %>
        </div>
        <div class="col-md-6">
            <%= f.password_field :password , class: 'form-control' %>
        </div>
    </div>
    <div class="row row-form">
        <div class="col-md-3 project-topic text-right">      
            <%= f.label :password_confirmation %>
        </div>
        <div class="col-md-6">
            <%= f.password_field :password_confirmation , class: 'form-control' %>
        </div>
    </div>
    <div class="row row-form">
        <div class="col-md-3 project-topic text-right">          
            <%= f.label :contact %>
        </div>
        <div class="col-md-6">
            <%= f.text_field :contact , class: 'form-control' %>
        </div>
    </div>
    <div class="row row-form">
        <div class="col-md-3 project-topic text-right">            
            <%= f.label :tel_number %>
        </div>
        <div class="col-md-6">
            <%= f.text_field :tel_number, class: 'form-control'  %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-right">
            <%= f.submit "Reset" ,class: 'button-link'%>
        </div>
        <div class="col-md-6 text-left">
            <%= f.submit "Create" , class: 'button-link' %>
        </div>        
    </div>
<% end %>

app/views/users/new.html.erb
<div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 5px;margin-bottom: 20px">Sign up</h3>
                    <%= render 'form', user: @user %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
    <div class="col-md-12">
        <div class="box-text-big" style="padding-bottom: 0px">
            <h3 class="project-topic text-center" style="margin-top: 5px">- Profile -</h3>
        </div>
     </div>
</div>
<div class="row">
    <div class="col-md-6 text-right">
            <p>Name : </p>
    </div>
    <div class="col-md-6 text-left">
            <p><%= @user.username %></p>
    </div>
</div>
<div class="row">
    <div class="col-md-6 text-right">
            <p>Telephone Number : </p>
    </div>
    <div class="col-md-6 text-left">
            <p><%= @user.tel_number %></p>
    </div>
</div>
<div class="row">
    <div class="col-md-6 text-right">
            <p>Contact : </p>
    </div>
    <div class="col-md-6 text-left">
            <p><%= @user.contact %></p>
    </div>
</div>
            